### ISSUE TITLE
ConvertTo-EnhancedHTMLFragment : Cannot bind argument to parameter 'InputObject' because it is null.

### ISSUE THREAD

**Issue by maro13** [microsoft/FastTrack#48] opened 2019-12-04 13:11 UTC
# Issue Details
Installed EnhancedHTML2 Module. Then Running Merge-SPMTResults.ps1 i get the following errors. 
NOTE: MYSERVER is name of our local file server.

.\Merge-SPMTResults.ps1 -Servers "MYSERVER" -GenerateHTMLReport -tenant mydomain.com

ConvertTo-EnhancedHTMLFragment : Cannot bind argument to parameter 'InputObject' because it is null.
At C:\Users\myaccount\AppData\Roaming\Microsoft\MigrationTool\mydomain.com\WF_a1a09fae\Report\TaskReport_c98174ca\Merge-SPMTResults.ps1:222 char:53
+ ... res = $Global:SummaryReports | ConvertTo-EnhancedHTMLFragment @params
+                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [ConvertTo-EnhancedHTMLFragment], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,ConvertTo-EnhancedHTMLFragment

ConvertTo-EnhancedHTMLFragment : Cannot bind argument to parameter 'InputObject' because it is null.
At C:\Users\myaccount\AppData\Roaming\Microsoft\MigrationTool\mydomains.com\WF_a1a09fae\Report\TaskReport_c98174ca\Merge-SPMTResults.ps1:237 char:51
+ ... res = $Global:FailureReports | ConvertTo-EnhancedHTMLFragment @params
+                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [ConvertTo-EnhancedHTMLFragment], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,ConvertTo-EnhancedHTMLFragment

**Comment by soyalejolopez** [comment] 2019-12-06 18:14
Hi @maro13  - thank you for bringing this up. Can you check if in the directory where you're running your script from, you have the following CSV files?  

"MergedFailureReport.csv"
"MergedSummaryReport.csv"

These are generated by the script.

**Comment by maro13** [comment] 2019-12-06 19:35
Hi @soyalejolopez. The only files that created are 
"Merge-SPMTResults-20191206.html"
"Merge-SPMTResoults-20191206.log"

The log says:
06/12/2019 19:58 : Reports location: C:\Users\myaccount\AppData\Roaming\Microsoft\MigrationTool\mydomain.com\WF_8de3339e\Report\TaskReport_edc0cb80

the HTML file says:
"Total File shares: Unable to retrieve data"

I actually ran the Preflight-OneDrive.ps1 and it worked. Does this script produce the same results, minus the total GBs that would be migrated?

**Comment by soyalejolopez** [comment] 2019-12-06 20:51
Thank you @maro13  - this issue is occurring likely because the script didn't find any SPMT Summary or Failure Reports to analyze. We've added a check for these reports so that it ends more gracefully. Please grab an updated version of the script and try again. 

Regarding Preflight-OneDrive.ps1, indeed, this script generates a similar HTML report.

**Comment by maro13** [comment] 2019-12-09 12:57
Thanks @soyalejolopez grabbed the updated script and yes indeed is says "No Summary Reports or Failure Reports from SPMT". Just to clarify.
1. We are planning a OneDrive for Business migration for our users so we're running this against our local home folder file share servers. 
2. We initiated a FastTrack with Microsoft and they pointed us to your script. 
3. When running SPMT, we are selecting the scan only report and not doing the migration yet. Here is the file structure from the SPMT that is created when i run a scan only SPMT.

C:\Users\myprofile\AppData\Roaming\Microsoft\MigrationTool\mydomain.com\WF_01f188bf\Report
GlobalSettings.csv
SummaryReport.csv


C:\Users\myprofile\AppData\Roaming\Microsoft\MigrationTool\mydomain.com\WF_01f188bf\Report\TaskReport_dee72de4 
ItemFailureReport_R1.csv
ItemReport_R1.csv
ItemReport_R1_002.csv
ItemReport_R1_003.csv
ItemReport_R1_004.csv
ItemSummary.csv
ScanSummary.csv
StructureReport_R1.csv

C:\Users\myprofile\AppData\Roaming\Microsoft\MigrationTool\mydomain.com\WF_01f188bf\Report\TaskReport_dee72de4\Details
TaskStatusEvents_R1.csv

**Comment by soyalejolopez** [comment] 2019-12-09 16:58
Thanks @maro13 - could you please grab an updated version of the script and share the results? Added some logging so we can dig into this. If easier, we can also work through your FastTrack contact so that we can jump on a call if easier.

**Comment by maro13** [comment] 2019-12-09 19:17
Output says "No Summary Reports or Failure Reports from SPMT Found. No data to process."  As i mentioned above, the files that are generated and the path is what i get when i run the scan option of the SPMT. 

I emailed our FastTrack contact to see if you could jump on a call. 

Thank you @soyalejolopez

**Comment by soyalejolopez** [comment] 2019-12-09 20:14
Using the latest version it should have also logged some additional details in the log file - do you have that log file handy? Issue is not reproducing in my lab, so we'll need to investigate what's causing the issue in your run. Will work with the FastTrack contact to see if we can line up a call and dig in.

**Comment by maro13** [comment] 2019-12-10 16:02
@soyalejolopez here is the log file that is created in the directory i'm running the script from. 
[Merge-SPMTResults-20191210.log](https://github.com/microsoft/FastTrack/files/3945811/Merge-SPMTResults-20191210.log)

**Comment by soyalejolopez** [comment] 2019-12-10 16:05
Thanks @maro13 - working with our FastTrack team to line up a call so we can dig into this. Stay tuned, more to come.

**Comment by patrick-rodgers** [comment] 2020-01-22 16:54
@soyalejolopez - any updates here?

**Comment by soyalejolopez** [comment] 2020-01-22 17:54
@patrick-rodgers thanks for the follow-up. 

@maro13 - any updates on this since we last chatted? Did the updated script help?

**Comment by maro13** [comment] 2020-01-23 18:09
@soyalejolopez Yes, it did help. Patrick and I are working on adding a file diff to the report as he mentioned we're seeing some inconsistencies. Will keep you posted.

**Comment by soyalejolopez** [comment] 2020-04-07 14:57
@maro13 - any updates on this one? Let us know if we can be of any add'l help.

**Closed** 2020-08-04 17:57 UTC
